# Generated by Django 5.2.2 on 2025-06-19 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otica_app', '0002_store_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_products', to='otica_app.product', verbose_name='Produto')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_products', to='otica_app.store', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Produto da Loja',
                'verbose_name_plural': 'Produtos das Lojas',
                'ordering': ['product__name'],
                'unique_together': {('store', 'product')},
            },
        ),
    ]
