# Generated by Django 5.2.2 on 2025-06-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otica_app', '0003_remove_product_quantity_remove_product_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('pix', 'PIX')], default='dinheiro', max_length=15, verbose_name='Forma de Pagamento'),
        ),
    ]
