# Generated by Django 4.2.7 on 2024-06-20 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otica_app', '0005_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='otica_app.seller', verbose_name='Vendedor'),
        ),
    ] 