# Generated by Django 5.2.2 on 2025-06-20 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otica_app', '0006_alter_sale_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTillSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Inicial')),
                ('final_amount_reported', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Final Informado')),
                ('final_amount_calculated', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Final Calculado')),
                ('difference', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diferença')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado')], default='aberto', max_length=10, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Fechado por')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Aberto por')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_till_sessions', to='otica_app.store', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Sessão de Caixa',
                'verbose_name_plural': 'Sessões de Caixa',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='cash_till_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='otica_app.cashtillsession', verbose_name='Sessão de Caixa'),
        ),
    ]
