# Generated by Django 4.2.7 on 2025-06-20 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otica_app', '0007_cashtillsession_sale_cash_till_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='cash_till_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_flows', to='otica_app.cashtillsession', verbose_name='Sessão de Caixa'),
        ),
    ]
