# Generated by Django 4.2.7 on 2025-06-24 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otica_app', '0012_cliente_alter_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='otica_app.cliente', verbose_name='Cliente'),
        ),
    ]
